/**
 * ===================================================================
 * JAI JINENDRA EVENTS - GALLERY IMAGE OPTIMIZER
 * ===================================================================
 * Run with:  npm run images          (only processes new / changed photos)
 *            npm run images -- --force   (rebuilds everything)
 *
 * Reads every original photo in   public/gallery/<category>/
 * and writes web-ready copies to  public/optimized/<category>/<name>-<width>.jpg
 *
 * - Applies the camera's EXIF rotation so portrait shots are never sideways
 * - Resizes 24-60 MP camera files down to 640 / 1280 / 1920 px wide (+2560 for landscape shots)
 *   (Lanczos resampling + light sharpening so they stay crisp)
 * - Never upscales small photos (e.g. WhatsApp copies) - they keep their size
 * - Writes js/image-manifest.js so the site can serve the right size per screen
 *
 * The originals in public/gallery/ are never modified.
 */

import sharp from 'sharp';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const SOURCE_DIR = 'public/gallery';
const OUTPUT_DIR = 'public/optimized';
const MANIFEST_FILE = 'js/image-manifest.js';
const WIDTHS = [640, 1280, 1920];
// Landscape photos also get a 2560px copy so full-screen heroes & the lightbox stay HD on large / retina screens
const LANDSCAPE_EXTRA_WIDTH = 2560;
const JPEG_QUALITY = 84;
const IMAGE_EXT = /\.(jpe?g|png|webp|tiff?|heic)$/i;
const FORCE = process.argv.includes('--force');

// "WhatsApp Image 2025-08-03 at 4.42.36 PM (1).jpeg" -> "whatsapp-image-2025-08-03-at-4-42-36-pm-1"
function slugify(fileName) {
  return path.parse(fileName).name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

async function isUpToDate(outputFile, sourceStat) {
  if (FORCE) return false;
  try {
    const outStat = await fs.stat(outputFile);
    return outStat.mtimeMs >= sourceStat.mtimeMs;
  } catch {
    return false;
  }
}

async function processImage(category, fileName) {
  const sourceFile = path.join(SOURCE_DIR, category, fileName);
  const sourceStat = await fs.stat(sourceFile);
  const meta = await sharp(sourceFile).metadata();

  // EXIF orientations 5-8 mean the stored pixels are rotated 90 degrees
  const rotated = (meta.orientation || 1) >= 5;
  const width = rotated ? meta.height : meta.width;
  const height = rotated ? meta.width : meta.height;

  const widths = width > height ? [...WIDTHS, LANDSCAPE_EXTRA_WIDTH] : WIDTHS;
  const targetWidths = widths.filter(w => w < width);
  if (width <= widths[widths.length - 1]) targetWidths.push(width);

  const slug = slugify(fileName);
  const variants = [];

  for (const targetWidth of targetWidths) {
    const outputFile = path.join(OUTPUT_DIR, category, `${slug}-${targetWidth}.jpg`);
    variants.push([targetWidth, outputFile.split(path.sep).join('/')]);

    if (await isUpToDate(outputFile, sourceStat)) continue;

    const scale = width / targetWidth;

    // Already web-sized & upright JPEG: copy as-is so it is not re-compressed a second time
    if (scale === 1 && meta.format === 'jpeg' && (meta.orientation || 1) === 1) {
      await fs.copyFile(sourceFile, outputFile);
      continue;
    }

    let pipeline = sharp(sourceFile).rotate();
    if (scale > 1) {
      pipeline = pipeline.resize({ width: targetWidth, kernel: 'lanczos3' });
      // Big reductions soften fine detail - a light unsharp mask restores crispness
      if (scale >= 2) pipeline = pipeline.sharpen({ sigma: 0.6 });
    }

    await pipeline
      .toColourspace('srgb')
      .jpeg({ quality: JPEG_QUALITY, mozjpeg: true, progressive: true })
      .toFile(outputFile);
  }

  return { width, height, variants };
}

async function main() {
  const manifest = {};
  const categories = (await fs.readdir(SOURCE_DIR, { withFileTypes: true }))
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort();

  for (const category of categories) {
    await fs.mkdir(path.join(OUTPUT_DIR, category), { recursive: true });
    const files = (await fs.readdir(path.join(SOURCE_DIR, category)))
      .filter(name => IMAGE_EXT.test(name))
      .sort();

    for (const fileName of files) {
      const key = `${SOURCE_DIR}/${category}/${fileName}`;
      try {
        const result = await processImage(category, fileName);
        manifest[key] = { w: result.width, h: result.height, srcset: result.variants };
        console.log(`  ok  ${key}  (${result.width}x${result.height} -> ${result.variants.map(v => v[0]).join(', ')})`);
      } catch (err) {
        console.error(`  !!  ${key}: ${err.message}`);
      }
    }
  }

  const banner = '// AUTO-GENERATED by `npm run images` (scripts/optimize-images.mjs) - do not edit by hand.\n' +
    '// Maps each original photo in public/gallery/ to its optimized, correctly-rotated web sizes.\n';
  const entries = Object.entries(manifest).map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)}`);
  await fs.writeFile(MANIFEST_FILE, `${banner}window.IMAGE_MANIFEST = {\n${entries.join(',\n')}\n};\n`);
  console.log(`\nDone: ${Object.keys(manifest).length} photos -> ${OUTPUT_DIR}/, manifest -> ${MANIFEST_FILE}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
